### ISSUE TITLE
Improve file management

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/AASP#23]
- [x] Show files by speaker
- [x] Users can delete files
- [x] Check that existing speaker / filename combinations are overwritten, i.e. repeated upload won't lead to duplicates

**Comment by jokke150** [comment]
Repeated upload leads to duplicates. This is desired behavior as there could be two speakers with the same name. The files can be deleted manually though

**Comment by BeritJanssen** [comment]
After discussion with @jokke150 , I agree that perhaps it's preferable to allow duplicate files. The problem was that there were trailing files which hadn't been removed after the associated database item was. This is now taken care of.

Since it's not easy to place an autogenerated primary key into a model after the fact, I decided to rewrite the initial migration, such that it's necessary to
- [ ] stop the Docker container
- [ ] find the postgres_data volume on the host system running `docker volume ls`
- [ ] remove that particular volume with `docker volume rm {postgres_data_volume_name}`
This is not the most elegant solution, but since we're only testing at this stage, it's not detrimental to do away with the existing databases.
